/**
 * Temporary ID utilities.
 *
 * New nodes/edges are created with a client-side temporary ID so the UI can
 * render optimistically; the server later assigns the real ID. Any code that
 * talks to the backend must treat temp IDs as "not yet persisted" and skip
 * per-entity mutations (POST upsert) until the real ID is assigned — otherwise
 * the server responds 404 (entity not found).
 *
 * Single source of truth for both the lib (sync hooks) and the app (canvas /
 * mobile editor). Keep prefix detection here so the two layers can never drift.
 */

/** Prefixes used by generateTempId. isTempId matches any of these. */
export const TEMP_ID_PREFIXES = ['temp_', 'edge_', 'node_'] as const;

// ============================================================
// Session temp-ID registry
// ============================================================
// Temp-ness is session runtime state, not ID format: temp-format IDs that
// leaked into POST /flows/:id/save are persisted server-side as canonical IDs,
// so a prefix check alone misclassifies them after reload. Only IDs generated
// by THIS session (and not yet resolved to a server ID) are truly temporary.
// Module-level so every hook instance (desktop canvas, mobile editor, save
// path) shares one view without prop plumbing.
// ============================================================

/** Every ID generated by generateTempId this session. */
const sessionTempIds = new Set<string>();

/** tempId -> server-assigned ID, once the create round-trip completes. */
const resolvedTempIds = new Map<string, string>();

/** Generate a client-side temporary ID (replaced by the server-assigned ID). */
export const generateTempId = (prefix: 'temp' | 'edge' | 'node' = 'temp'): string => {
    const id = `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
    sessionTempIds.add(id);
    return id;
};

/** Record that the server assigned a real ID for a temp ID created this session. */
export const markTempIdResolved = (tempId: string, serverId: string): void => {
    resolvedTempIds.set(tempId, serverId);
};

/**
 * True only for IDs generated this session whose server create has not completed.
 * Temp-format IDs loaded from the server (historical leaks) return false — they
 * are canonical server IDs and must not be excluded from syncs or saves.
 */
export const isUnresolvedTempId = (id: string | undefined): boolean => {
    if (!id) return false;
    return sessionTempIds.has(id) && !resolvedTempIds.has(id);
};

/** Map a resolved temp ID to its server ID; any other ID passes through unchanged. */
export const resolveTempId = (id: string): string => resolvedTempIds.get(id) ?? id;

/** Test-only: clear the session registry. */
export const __resetTempIdRegistry = (): void => {
    sessionTempIds.clear();
    resolvedTempIds.clear();
};

/**
 * Check if an ID has the temporary-ID format.
 * @deprecated For gating server mutations use isUnresolvedTempId — format alone
 * cannot distinguish a pending create from a server-persisted historical leak.
 */
export const isTempId = (id: string | undefined): boolean => {
    if (!id) return false;
    return TEMP_ID_PREFIXES.some(prefix => id.startsWith(prefix));
};
