import type { Block } from '../types';

export const MOCK_BLOCKS: Block[] = [
    {
        id: '0008',
        createdAt: 1770649201803,
        updatedAt: 1773070187790,
        deletedAt: 0,
        stereo: 'input',
        name: '텍스트 입력',
        label: '텍스트 입력',
        icon: '📝',
        description: 'User Text Input - pass-through text input block',
        order: 100,
        processType: 'input-text',
        input$: [],
        output$: [{ id: 'out', label: '텍스트', type: 'text' }],
        config$: [
            {
                key: 'text',
                type: 'text',
                label: '텍스트',
                placeholder: '입력이 연결되지 않은 경우 사용되는 텍스트',
                defaultValue: 'Hello World',
            },
        ],
        isFrontend: true,
    },
    {
        id: '0009',
        createdAt: 1770649201813,
        updatedAt: 1773070187790,
        deletedAt: 0,
        stereo: 'input',
        name: '이미지 입력',
        label: '이미지 입력',
        icon: '🖼️',
        description: 'User Image Input - pass-through image input block',
        order: 110,
        processType: 'input-image',
        input$: [],
        output$: [{ id: 'out', label: '이미지', type: 'image' }],
        config$: [
            {
                key: 'imageData',
                type: 'file',
                label: '이미지',
                placeholder: '입력이 연결되지 않은 경우 사용되는 이미지',
                defaultValue: '',
            },
            {
                key: 'aspectRatio',
                type: 'select',
                label: '가로 세로 비율',
                options: [
                    { label: '3:4', value: '3:4' },
                    { label: '4:3', value: '4:3' },
                    { label: '1:1', value: '1:1' },
                    { label: '9:16', value: '9:16' },
                    { label: '16:9', value: '16:9' },
                ],
                placeholder: '이미지의 가로 세로 비율을 선택하세요',
                defaultValue: '3:4',
            },
            {
                key: 'maxWidth',
                type: 'number',
                label: '최대 너비',
                placeholder: '이미지의 최대 너비를 픽셀 단위로 입력하세요 (ex: 1000)',
                defaultValue: '1000',
            },
            {
                key: 'bypass',
                type: 'boolean',
                label: '처리 우회',
                defaultValue: 'false',
            },
        ],
        isFrontend: true,
    },
    {
        id: '0026',
        createdAt: 1771078347514,
        updatedAt: 1774019917375,
        deletedAt: 0,
        stereo: 'process',
        name: 'Html 업로드',
        label: 'Html 업로드',
        icon: '⤴️',
        description: 'Upload html via eureka codes',
        order: 120,
        processType: 'upload-html',
        input$: [{ id: 'in', label: 'HTML', type: 'any' }],
        output$: [{ id: 'out', label: '링크', type: 'text' }],
        config$: [
            { key: 'projectId', type: 'text', label: '프로젝트 ID (projectId)', short: 1, defaultValue: '' },
            { key: 'title', type: 'text', label: '타이틀 (title)', short: 1 },
            { key: 'version', type: 'text', label: '버전 (version)', short: 1 },
            { key: 'description', type: 'text', label: '설명 (description)' },
            { key: 'autoDeploy', type: 'boolean', label: '자동 배포', defaultValue: 'true' },
        ],
        isFrontend: false,
    },
    {
        id: '0010',
        createdAt: 1770649201812,
        updatedAt: 1773070187807,
        deletedAt: 0,
        stereo: 'process',
        name: '버퍼 (지연)',
        label: '버퍼 (지연)',
        icon: '⌛️',
        description: 'Buffer (Delay) - delays the input packet by a configured duration',
        order: 200,
        processType: 'buffer',
        input$: [{ id: 'in', label: '입력', type: 'any' }],
        output$: [{ id: 'out', label: '출력', type: 'any' }],
        config$: [
            {
                key: 'delayMs',
                type: 'number',
                label: '지연 (ms)',
                placeholder: '전달 전에 대기할 밀리초 단위의 시간 (기본값: 3s)',
                defaultValue: '3000',
            },
        ],
        isFrontend: false,
    },
    {
        id: '0007',
        createdAt: 1770649201809,
        updatedAt: 1773070187773,
        deletedAt: 0,
        stereo: 'process',
        name: 'AI 단일 출력 생성기',
        label: 'AI 단일 출력 생성기',
        icon: '🧠',
        description: 'AI Single Output Generator Processor - generates a single output using Gemini API',
        order: 400,
        processType: 'single-output-generator',
        input$: [
            { id: 'prompt', label: '프롬프트', type: 'text' },
            { id: 'schema', label: '스키마', type: 'text' },
            { id: 'image0', label: '이미지 1', type: 'image' },
            { id: 'image1', label: '이미지 2', type: 'image' },
            { id: 'image2', label: '이미지 3', type: 'image' },
            { id: 'image3', label: '이미지 4', type: 'image' },
            { id: 'image4', label: '이미지 5', type: 'image' },
        ],
        output$: [
            { id: 'out', label: '결과', type: 'text' },
            { id: 'err', label: '오류', type: 'text' },
        ],
        config$: [
            {
                key: 'model',
                type: 'select',
                label: '생성 모델',
                options: [
                    { label: 'Gemini 2.5 Flash', value: 'gemini-2.5-flash' },
                    { label: 'Gemini 2.5 Pro', value: 'gemini-2.5-pro' },
                    { label: 'Gemini 3 Flash', value: 'gemini-3-flash-preview' },
                    { label: 'Gemini 3.1 Pro', value: 'gemini-3.1-pro-preview' },
                ],
                defaultValue: 'gemini-2.5-flash',
            },
            { key: 'pro', type: 'boolean', label: 'Pro Mode' },
            { key: 'system', type: 'text', label: 'System Prompt' },
            { key: 'temperature', type: 'number', label: 'Temperature' },
            { key: 'topP', type: 'number', label: 'Top P' },
            { key: 'topK', type: 'number', label: 'Top K' },
        ],
        isFrontend: false,
    },
    {
        id: '0006',
        createdAt: 1770649201806,
        updatedAt: 1773070187773,
        deletedAt: 0,
        stereo: 'process',
        name: 'AI 이미지 생성기',
        label: 'AI 이미지 생성기',
        icon: '🖼️',
        description: 'AI Single Image Generator Processor - generates a single image using Gemini API',
        order: 410,
        processType: 'single-image-generator',
        input$: [
            { id: 'prompt', label: '프롬프트', type: 'text' },
            { id: 'image0', label: '이미지 1', type: 'image' },
            { id: 'image1', label: '이미지 2', type: 'image' },
            { id: 'image2', label: '이미지 3', type: 'image' },
            { id: 'image3', label: '이미지 4', type: 'image' },
            { id: 'image4', label: '이미지 5', type: 'image' },
        ],
        output$: [
            { id: 'out', label: '결과', type: 'image' },
            { id: 'err', label: '오류', type: 'text' },
        ],
        config$: [
            {
                key: 'model',
                type: 'select',
                label: '생성 모델',
                options: [
                    { label: 'Default', value: 'gemini-default' },
                    { label: 'Nano Banana', value: 'gemini-2.5-flash-image' },
                    { label: 'GPT Image', value: 'gpt-image-1' },
                ],
                defaultValue: 'gemini-2.5-flash',
            },
            { key: 'pro', type: 'boolean', label: 'Pro Mode' },
            { key: 'system', type: 'text', label: '시스템 프롬프트' },
            {
                key: 'aspectRatio',
                type: 'select',
                label: '가로 세로 비율',
                options: [
                    { label: '3:4', value: '3:4' },
                    { label: '4:3', value: '4:3' },
                    { label: '1:1', value: '1:1' },
                    { label: '9:16', value: '9:16' },
                    { label: '16:9', value: '16:9' },
                ],
                defaultValue: '1:1',
            },
            {
                key: 'imageSize',
                type: 'select',
                label: '이미지 크기',
                options: [
                    { label: '1K', value: '1K' },
                    { label: '2K', value: '2K' },
                    { label: '4K', value: '4K' },
                ],
                defaultValue: '1K',
            },
        ],
        isFrontend: false,
    },
    {
        id: '0025',
        createdAt: 1771078347515,
        updatedAt: 1773070187838,
        deletedAt: 0,
        stereo: 'process',
        name: 'AI JSON 스키마 변환기',
        label: 'AI JSON 스키마 변환기',
        icon: '🧩',
        description: 'AI JSON Schema Converter Processor - converts a JSON schema using Gemini API',
        order: 800,
        processType: 'schema-json-converter',
        input$: [{ id: 'code', label: 'AI 코드', type: 'text' }],
        output$: [{ id: 'out', label: 'JSON 스키마', type: 'text' }],
        config$: [{ key: 'system', type: 'text', label: '시스템 프롬프트' }],
        isFrontend: false,
    },
    {
        id: '0024',
        createdAt: 1771078347516,
        updatedAt: 1773070187824,
        deletedAt: 0,
        stereo: 'process',
        name: '템플릿 텍스트 생성기 (Mustache)',
        label: '템플릿 텍스트 생성기 (Mustache)',
        icon: '🥸',
        description: 'Mustache 템플릿 엔진을 사용하여 텍스트를 생성하는 프로세서',
        order: 810,
        processType: 'mustache-text-generator',
        input$: [
            { id: 'in', label: '템플릿', type: 'text' },
            { id: 'p0', label: '1번째 입력', type: 'text' },
            { id: 'p1', label: '2번째 입력', type: 'text' },
            { id: 'p2', label: '3번째 입력', type: 'text' },
            { id: 'p3', label: '4번째 입력', type: 'text' },
            { id: 'p4', label: '5번째 입력', type: 'text' },
        ],
        output$: [{ id: 'out', label: '생성된 텍스트', type: 'text' }],
        config$: [
            { key: 'text0', type: 'text', label: '1번째 입력의 텍스트 이름', short: 1 },
            { key: 'text1', type: 'text', label: '2번째 입력의 텍스트 이름', short: 1 },
            { key: 'text2', type: 'text', label: '3번째 입력의 텍스트 이름', short: 1 },
            { key: 'text3', type: 'text', label: '4번째 입력의 텍스트 이름', short: 1 },
            { key: 'text4', type: 'text', label: '5번째 입력의 텍스트 이름', short: 1 },
        ],
        isFrontend: false,
    },
    {
        id: '0015',
        createdAt: 1770649201951,
        updatedAt: 1773070187823,
        deletedAt: 0,
        stereo: 'output',
        name: '미리보기',
        label: '미리보기',
        icon: '🔍',
        description: '미리보기 - UI 미리보기용 터미널 출력 블록',
        order: 900,
        processType: 'output-preview',
        input$: [{ id: 'in', label: '입력', type: 'any' }],
        output$: [],
        config$: [],
        isFrontend: true,
    },
    {
        id: '0014',
        createdAt: 1770649201952,
        updatedAt: 1773070187807,
        deletedAt: 0,
        stereo: 'output',
        name: '디버그 로그',
        label: '디버그 로그',
        icon: '🪵',
        description: '디버그 로그 - 입력을 서버 콘솔에 출력 (터미널 노드)',
        order: 999,
        processType: 'output-console',
        input$: [{ id: 'in', label: '입력', type: 'any' }],
        output$: [],
        config$: [
            {
                key: 'prefix',
                type: 'text',
                label: '접두사',
                placeholder: '로그 접두사 문자열 (기본값: "Log:")',
                defaultValue: 'Log:',
            },
        ],
        isFrontend: true,
    },
];
