import type { Tool } from '../types';

export const MOCK_TOOLS: Tool[] = [
    {
        id: '0001',
        createdAt: 1770649201000,
        updatedAt: 1770649201000,
        deletedAt: 0,
        name: 'read_file',
        label: '파일 읽기',
        icon: '📖',
        category: 'file',
        description:
            '로컬 파일시스템에서 파일을 읽습니다. 절대 경로를 받아 파일 내용을 반환하며, 줄 번호와 함께 출력합니다. offset과 limit으로 부분 읽기를 지원합니다.',
        parameters: [
            { name: 'file_path', type: 'string', description: '읽을 파일의 절대 경로', required: true },
            { name: 'offset', type: 'number', description: '읽기 시작할 줄 번호', required: false },
            { name: 'limit', type: 'number', description: '읽을 줄 수', required: false },
        ],
        isEnabled: true,
    },
    {
        id: '0002',
        createdAt: 1770649202000,
        updatedAt: 1770649202000,
        deletedAt: 0,
        name: 'write_file',
        label: '파일 쓰기',
        icon: '✏️',
        category: 'file',
        description:
            '파일을 생성하거나 덮어씁니다. 기존 파일이 있으면 전체를 교체하며, 새 파일이면 생성합니다. 기존 파일 수정 시에는 Edit 도구를 우선 사용하세요.',
        parameters: [
            { name: 'file_path', type: 'string', description: '쓸 파일의 절대 경로', required: true },
            { name: 'content', type: 'string', description: '파일에 쓸 내용', required: true },
        ],
        isEnabled: true,
    },
    {
        id: '0003',
        createdAt: 1770649203000,
        updatedAt: 1770649203000,
        deletedAt: 0,
        name: 'edit_file',
        label: '파일 편집',
        icon: '🔧',
        category: 'file',
        description:
            '문자열 치환 방식으로 파일을 수정합니다. old_string을 new_string으로 교체하며, 고유한 문자열 매칭이 필요합니다. replace_all 옵션으로 전체 치환이 가능합니다.',
        parameters: [
            { name: 'file_path', type: 'string', description: '수정할 파일의 절대 경로', required: true },
            { name: 'old_string', type: 'string', description: '교체할 기존 문자열', required: true },
            { name: 'new_string', type: 'string', description: '새로 바꿀 문자열', required: true },
            { name: 'replace_all', type: 'boolean', description: '모든 발생을 교체할지 여부', required: false },
        ],
        isEnabled: true,
    },
    {
        id: '0004',
        createdAt: 1770649204000,
        updatedAt: 1770649204000,
        deletedAt: 0,
        name: 'search_files',
        label: '파일 검색',
        icon: '🔎',
        category: 'search',
        description:
            'glob 패턴을 사용하여 파일을 검색합니다. **/*.ts, src/**/*.tsx 등의 패턴을 지원하며, 수정 시간순으로 결과를 반환합니다.',
        parameters: [
            { name: 'pattern', type: 'string', description: '검색할 glob 패턴', required: true },
            { name: 'path', type: 'string', description: '검색할 디렉토리 경로', required: false },
        ],
        isEnabled: true,
    },
    {
        id: '0005',
        createdAt: 1770649205000,
        updatedAt: 1770649205000,
        deletedAt: 0,
        name: 'search_content',
        label: '내용 검색',
        icon: '🔍',
        category: 'search',
        description:
            '정규식 패턴으로 파일 내용을 검색합니다. ripgrep 기반으로 빠르게 동작하며, 파일 타입 필터링과 컨텍스트 라인 표시를 지원합니다.',
        parameters: [
            { name: 'pattern', type: 'string', description: '검색할 정규식 패턴', required: true },
            { name: 'path', type: 'string', description: '검색할 파일 또는 디렉토리', required: false },
            { name: 'glob', type: 'string', description: '파일 필터 glob 패턴', required: false },
        ],
        isEnabled: true,
    },
    {
        id: '0006',
        createdAt: 1770649206000,
        updatedAt: 1770649206000,
        deletedAt: 0,
        name: 'run_command',
        label: '명령 실행',
        icon: '⚡',
        category: 'system',
        description:
            '셸 명령을 실행하고 결과를 반환합니다. 작업 디렉토리는 명령 간에 유지되며, 타임아웃 설정과 백그라운드 실행을 지원합니다.',
        parameters: [
            { name: 'command', type: 'string', description: '실행할 셸 명령', required: true },
            { name: 'timeout', type: 'number', description: '타임아웃 (밀리초)', required: false },
            { name: 'run_in_background', type: 'boolean', description: '백그라운드 실행 여부', required: false },
        ],
        isEnabled: true,
    },
    {
        id: '0007',
        createdAt: 1770649207000,
        updatedAt: 1770649207000,
        deletedAt: 0,
        name: 'web_search',
        label: '웹 검색',
        icon: '🌐',
        category: 'web',
        description: '웹에서 정보를 검색합니다. 최신 문서, 라이브러리 사용법, 에러 해결 방법 등을 찾을 때 활용합니다.',
        parameters: [
            { name: 'query', type: 'string', description: '검색 쿼리', required: true },
            { name: 'max_results', type: 'number', description: '최대 결과 수', required: false },
        ],
        isEnabled: true,
    },
    {
        id: '0008',
        createdAt: 1770649208000,
        updatedAt: 1770649208000,
        deletedAt: 0,
        name: 'web_fetch',
        label: '웹 페이지 가져오기',
        icon: '📥',
        category: 'web',
        description:
            'URL에서 콘텐츠를 가져옵니다. 웹 페이지, API 응답, 문서 등을 직접 읽을 수 있으며, HTML을 마크다운으로 변환하여 반환합니다.',
        parameters: [
            { name: 'url', type: 'string', description: '가져올 URL', required: true },
            { name: 'format', type: 'string', description: '출력 형식 (text, markdown)', required: false },
        ],
        isEnabled: true,
    },
    {
        id: '0009',
        createdAt: 1770649209000,
        updatedAt: 1770649209000,
        deletedAt: 0,
        name: 'code_analysis',
        label: '코드 분석',
        icon: '🧠',
        category: 'code',
        description:
            '코드베이스의 구조와 의존성을 분석합니다. 파일 간 관계, 임포트 그래프, 함수 호출 체인 등을 파악하여 아키텍처를 이해합니다.',
        parameters: [
            { name: 'target', type: 'string', description: '분석할 파일 또는 디렉토리 경로', required: true },
            { name: 'depth', type: 'number', description: '분석 깊이', required: false },
        ],
        isEnabled: true,
    },
    {
        id: '0010',
        createdAt: 1770649210000,
        updatedAt: 1770649210000,
        deletedAt: 0,
        name: 'data_transform',
        label: '데이터 변환',
        icon: '🔄',
        category: 'data',
        description:
            'JSON, CSV, YAML 등 데이터 형식 간 변환을 수행합니다. 스키마 변환, 데이터 매핑, 포맷 정리 등을 지원합니다.',
        parameters: [
            { name: 'input', type: 'string', description: '변환할 입력 데이터', required: true },
            { name: 'from_format', type: 'string', description: '입력 형식', required: true },
            { name: 'to_format', type: 'string', description: '출력 형식', required: true },
        ],
        isEnabled: true,
    },
];
